name: Continuous Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linter-prettier-tsc:
    runs-on: ubuntu-latest
    steps:
      - name: Clone expense-manager
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Run linter
        run: pnpm run lint
      - name: Run prettier
        run: pnpm run prettier
      - name: Run TypeScript
        run: pnpm run typescript

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone expense-manager
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.1
      - name: Create .env-dev
        env:
          ENV_SECRETS: ${{ secrets.ENV_SECRETS }}
        # This seems to be the easiest way: https://stackoverflow.com/a/64452700/7227455
        run: echo $ENV_SECRETS | base64 -d > .env-dev
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Run unit tests
        run: pnpm run test:unit

  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Clone expense-manager
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.1
      - name: Create .env-dev
        env:
          ENV_SECRETS: ${{ secrets.ENV_SECRETS }}
        # This seems to be the easiest way: https://stackoverflow.com/a/64452700/7227455
        run: echo $ENV_SECRETS | base64 -d > .env-dev
      - name: Create serviceAccount.json
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        # This seems to be the easiest way: https://stackoverflow.com/a/64452700/7227455
        run: echo $SERVICE_ACCOUNT | base64 -d > serviceAccount.json
      - name: Run cypress tests
        uses: cypress-io/github-action@v4
        with:
          build: pnpm test:e2e:ci:build-app
          start: pnpm test:e2e:ci:start-app
          wait-on: 'http://localhost:3000'
          # Unfortunately, videos do not work on the default GitHub actions runner. See:
          # https://github.com/cypress-io/cypress/issues/19488
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
